name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build site
        run: |
          # API 디렉토리 생성
          mkdir -p api
          
          # 초기 progress.json 생성 (없는 경우)
          if [ ! -f api/progress.json ]; then
            echo '{}' > api/progress.json
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2