name: Update Progress Data

on:
  schedule:
    # 매일 자정에 실행
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'api/progress.json'

jobs:
  update-progress:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Generate progress data
      run: |
        python scripts/generate_progress.py
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add api/progress.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update progress data [skip ci]" && git push)